// SPDX-FileCopyrightText: 2022 M. Shulhan <ms@kilabit.info>
// SPDX-License-Identifier: GPL-3.0-or-later
= gotp changelog
Shulhan <ms@kilabit.info>
:toc:
:sectanchors:
:sectlinks:

[#v0_3_1]
== gotp v0.3.1 (2023-05-25)

[#v0_3_1__bug_fix]
===  Bug fix

all: load private key only when needed::
+
--
In case the configuration use private key with passphrase, the bash
completion will hang due to the command ask for passphrase.

This changes fix this issue by loading private key only when doing add,
generate, import, or remote-private-key.
--


[#v0_3_0]
== gotp v0.3.0 (2023-05-17)

[#v0_3_0__new_features]
=== New features

all: add command to remove the private key::
+
The remove-private-key decrypt the issuer's value back using previous
private key and store it back to file as plain text.

all: add command to set private key::
+
The set-private-key command encrypt the issuer's value (hash:secret...)
in the file using private key.
The supported private key is RSA.

[#v0_3_0__chores]
=== Chores

all: update Go version to 1.19 and all dependencies::


[#v0_2_3]
== gotp v0.2.3 (2023-02-12)

[#v0_2_3_enhancements]
===  Enhancements

all: add bash completion script::

[#v0_2_3_chores]
===  Chores

all: move the installation steps in AUR to Makefile::


make: change the build and install directory::
+
The build task now create binary under _sys/usr/bin/, while the install
task install the binary based on $DESTDIR environment variable, not $GOBIN.


[#v0_2_2]
== gotp v0.2.2 (2022-09-06)

[#v0_2_2_bug_fix]
=== Bug fix

all: fix the go:embed reference to symbolic link::
+
Due to previous commit, where we rename the README.adoc to README, and
change it to symbolic link, the build then failed when doing go:embed.

[#v0_2_2_chores]
=== Chores

all: add task to serve and preview the documentation at _doc::

all: group all documents into directory _doc::


[#v0_2_1]
== gotp v0.2.1 (2022-08-07)

[#v0_2_1_bug_fixes]
===  Bug fixes

all: fix base32 decoding on secret::
+
--
The base32 decoding should be without padding otherwise it will return
an error (for some base32 string):

	illegal base32 data at input byte XX
--

[#v0_2_1_chores]
===  Chores

_AUR: add package build for Arch Linux::
This package build the gotp based on the latest tag and commit.

go.mod: set minimum Go version to 1.18 and update all modules::
+
--
The 1.17 has been deprecated since the release of 1.19.

This update affect the test cases on Cli.
--

[#v0_2_0]
== gotp v0.2.0 (2022-03-14)

Release gotp under GPL 3.0 or later.

See https://kilabit.info/journal/2022/gpl/ for more information.


[#v0_1_0]
== gotp v0.1.0 (2022-02-08)

The first release of gotp, a command line interface to manage and generate
Time-based One Time Password (TOTP).

Features,

* Add a TOTP secret identified by unique LABEL.
* Generate N number passwords using the secret identified by LABEL.
* Import the TOTP configuration from other provider.
  Currently, the only supported PROVIDER is Aegis and the supported file
  is .txt.
* List all labels stored in the configuration.
* Remove LABEL from configuration.
* Rename a LABEL into NEW-LABEL.
* Encrypted secret using RSA based private key.
